
name: 'covid_cz'
version: '1.0.0'
config-version: 2

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

models:
    materialized: table
    covid_mv:
        materialized: table
    covid_os:
        materialized: table
    covid_v:
        materialized: view
    geo_mv:
        materialized: table
    geo_os:
        materialized: table